### ISSUE TITLE
Bug au niveau de l'indentation

### ISSUE THREAD

**Issue by LucasKeure** [coca44/My_config#1]
Bravo pour avoir corriger l'erreur au niveau des tableau mais par contre je crois que sa a casser le check d'indentation
![screenshot from 2017-10-31 11-42-29](https://user-images.githubusercontent.com/9662079/32220093-b86b1e90-be30-11e7-8683-cd5e2c6a8025.png)

**Comment by LucasKeure** [comment]
J'ai plus d'info, le problème survient des qu'ont a un else avec deux crochets:
} else {
Et fais buger toute les lignes suivantes

**Comment by coca44** [comment]
Yeap je suis au courant des gens de ma promo me l'ont signalé, je vais corrigé cela ! :)

**Comment by coca44** [comment]
Il me semble que je l'ai corrigé en corrigeant autre chose, peux tu retester sur ton code ? :)
@LucasKeure

**Comment by LucasKeure** [comment]
Y'a des bugs en moins mais au niveau du else c'est toujours bugger

**Comment by coca44** [comment]
@LucasKeure Merci, je m'en occupe dès que j'ai un peu de temps ! :)
