### ISSUE TITLE
Bug - Declaration of variables...

### ISSUE THREAD

**Issue by BaconsWizard** [coca44/My_config#2]
there is another issue when I declare some variables or I want to change the value just before a return...
![screenshot from 2017-11-01 18-15-49](https://user-images.githubusercontent.com/33158297/32287934-9ced4e7e-bf32-11e7-8afc-263ba5204f75.png)
![screenshot from 2017-11-01 18-24-13](https://user-images.githubusercontent.com/33158297/32287937-9ddb60d2-bf32-11e7-8d9f-78f9e91be79f.png)

**Comment by coca44** [comment]
I know this bug, I'm going to correct that when I've some times ! :)

Thank you
