### ISSUE TITLE
[src/flags.c:15] Espaces manquants autours d'un opérateur

### ISSUE THREAD

**Issue by Eldriann** [coca44/My_config#7]
14        char *error_str = my_strdup("my_ls: invalid option -- '?'\n\                                                                                                                          
15Try './my_ls --help' for more information.\n");
16

**Comment by NahisWayard** [comment]
void display_usage(void)
{
	my_putstr("USAGE\n\t./my_sokoban map\nDESCRIPTION\n\tmap file \
representing the warehouse map, containing ‘#’ for walls,\n\t‘P’ for the \
player, ‘X’ for boxes and ‘O’ for storage locations.\n");
}

**Comment by coca44** [comment]
Ignore between "

**Comment by coca44** [comment]
Also in multiline

**Comment by coca44** [comment]
Corrected
